/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games/index'
import { Route as AuthenticatedGamesCategoriesRouteImport } from './routes/_authenticated/games/categories'
import { Route as AuthenticatedGamesRankingRouteImport } from './routes/_authenticated/games/ranking'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players/index'
import { Route as AuthenticatedPlayersGroupsRouteImport } from './routes/_authenticated/players/groups'
import { Route as AuthenticatedPlayersLabelsRouteImport } from './routes/_authenticated/players/labels'
import { Route as AuthenticatedPlayersMobilePolicyRouteImport } from './routes/_authenticated/players/mobile-policy'
import { Route as AuthenticatedPlayersSelfLimitsRouteImport } from './routes/_authenticated/players/self-limits'
import { Route as AuthenticatedPlayersSessionsRouteImport } from './routes/_authenticated/players/sessions'
import { Route as AuthenticatedPromotionsIndexRouteImport } from './routes/_authenticated/promotions/index'
import { Route as AuthenticatedPromotionsBannersRouteImport } from './routes/_authenticated/promotions/banners'
import { Route as AuthenticatedPromotionsBonusesRouteImport } from './routes/_authenticated/promotions/bonuses'
import { Route as AuthenticatedPromotionsPagesRouteImport } from './routes/_authenticated/promotions/pages'
import { Route as AuthenticatedPromotionsRebateSettingRouteImport } from './routes/_authenticated/promotions/rebate-setting'
import { Route as AuthenticatedPromotionsRebateTransRouteImport } from './routes/_authenticated/promotions/rebate-trans'
import { Route as AuthenticatedPromotionsTransactionsRouteImport } from './routes/_authenticated/promotions/transactions'
import { Route as AuthenticatedPromotionsXpShopRouteImport } from './routes/_authenticated/promotions/xp-shop'
import { Route as AuthenticatedPromotionsXpShopCategoriesRouteImport } from './routes/_authenticated/promotions/xp-shop-categories'
import { Route as AuthenticatedPromotionsXpShopHistoryRouteImport } from './routes/_authenticated/promotions/xp-shop-history'
import { Route as AuthenticatedReportsAcscRewardPushlogRouteImport } from './routes/_authenticated/reports/acsc-reward-pushlog'
import { Route as AuthenticatedReportsAcscTransferRouteImport } from './routes/_authenticated/reports/acsc-transfer'
import { Route as AuthenticatedReportsBetTransRouteImport } from './routes/_authenticated/reports/bet-trans'
import { Route as AuthenticatedReportsLedgerTransRouteImport } from './routes/_authenticated/reports/ledger-trans'
import { Route as AuthenticatedReportsPaymentTransactionRouteImport } from './routes/_authenticated/reports/payment-transaction'
import { Route as AuthenticatedReportsWagerStatsRouteImport } from './routes/_authenticated/reports/wager-stats'
import { Route as AuthenticatedSettingsAdminOpsLogsRouteImport } from './routes/_authenticated/settings/admin-ops-logs'
import { Route as AuthenticatedSettingsAdminQuotaConfigsRouteImport } from './routes/_authenticated/settings/admin-quota-configs'
import { Route as AuthenticatedSettingsAdminQuotasRouteImport } from './routes/_authenticated/settings/admin-quotas'
import { Route as AuthenticatedSettingsAdminSessionsRouteImport } from './routes/_authenticated/settings/admin-sessions'
import { Route as AuthenticatedSettingsAdminsRouteImport } from './routes/_authenticated/settings/admins'
import { Route as AuthenticatedSettingsPaymentChannelsRouteImport } from './routes/_authenticated/settings/payment-channels'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsRolesPermissionRouteImport } from './routes/_authenticated/settings/roles-permission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesCategoriesRoute =
  AuthenticatedGamesCategoriesRouteImport.update({
    id: '/games/categories',
    path: '/games/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamesRankingRoute =
  AuthenticatedGamesRankingRouteImport.update({
    id: '/games/ranking',
    path: '/games/ranking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersGroupsRoute =
  AuthenticatedPlayersGroupsRouteImport.update({
    id: '/players/groups',
    path: '/players/groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersLabelsRoute =
  AuthenticatedPlayersLabelsRouteImport.update({
    id: '/players/labels',
    path: '/players/labels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersMobilePolicyRoute =
  AuthenticatedPlayersMobilePolicyRouteImport.update({
    id: '/players/mobile-policy',
    path: '/players/mobile-policy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersSelfLimitsRoute =
  AuthenticatedPlayersSelfLimitsRouteImport.update({
    id: '/players/self-limits',
    path: '/players/self-limits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersSessionsRoute =
  AuthenticatedPlayersSessionsRouteImport.update({
    id: '/players/sessions',
    path: '/players/sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsIndexRoute =
  AuthenticatedPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsBannersRoute =
  AuthenticatedPromotionsBannersRouteImport.update({
    id: '/promotions/banners',
    path: '/promotions/banners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsBonusesRoute =
  AuthenticatedPromotionsBonusesRouteImport.update({
    id: '/promotions/bonuses',
    path: '/promotions/bonuses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsPagesRoute =
  AuthenticatedPromotionsPagesRouteImport.update({
    id: '/promotions/pages',
    path: '/promotions/pages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsRebateSettingRoute =
  AuthenticatedPromotionsRebateSettingRouteImport.update({
    id: '/promotions/rebate-setting',
    path: '/promotions/rebate-setting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsRebateTransRoute =
  AuthenticatedPromotionsRebateTransRouteImport.update({
    id: '/promotions/rebate-trans',
    path: '/promotions/rebate-trans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsTransactionsRoute =
  AuthenticatedPromotionsTransactionsRouteImport.update({
    id: '/promotions/transactions',
    path: '/promotions/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsXpShopRoute =
  AuthenticatedPromotionsXpShopRouteImport.update({
    id: '/promotions/xp-shop',
    path: '/promotions/xp-shop',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsXpShopCategoriesRoute =
  AuthenticatedPromotionsXpShopCategoriesRouteImport.update({
    id: '/promotions/xp-shop-categories',
    path: '/promotions/xp-shop-categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsXpShopHistoryRoute =
  AuthenticatedPromotionsXpShopHistoryRouteImport.update({
    id: '/promotions/xp-shop-history',
    path: '/promotions/xp-shop-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsAcscRewardPushlogRoute =
  AuthenticatedReportsAcscRewardPushlogRouteImport.update({
    id: '/reports/acsc-reward-pushlog',
    path: '/reports/acsc-reward-pushlog',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsAcscTransferRoute =
  AuthenticatedReportsAcscTransferRouteImport.update({
    id: '/reports/acsc-transfer',
    path: '/reports/acsc-transfer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsBetTransRoute =
  AuthenticatedReportsBetTransRouteImport.update({
    id: '/reports/bet-trans',
    path: '/reports/bet-trans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsLedgerTransRoute =
  AuthenticatedReportsLedgerTransRouteImport.update({
    id: '/reports/ledger-trans',
    path: '/reports/ledger-trans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsPaymentTransactionRoute =
  AuthenticatedReportsPaymentTransactionRouteImport.update({
    id: '/reports/payment-transaction',
    path: '/reports/payment-transaction',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsWagerStatsRoute =
  AuthenticatedReportsWagerStatsRouteImport.update({
    id: '/reports/wager-stats',
    path: '/reports/wager-stats',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAdminOpsLogsRoute =
  AuthenticatedSettingsAdminOpsLogsRouteImport.update({
    id: '/settings/admin-ops-logs',
    path: '/settings/admin-ops-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAdminQuotaConfigsRoute =
  AuthenticatedSettingsAdminQuotaConfigsRouteImport.update({
    id: '/settings/admin-quota-configs',
    path: '/settings/admin-quota-configs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAdminQuotasRoute =
  AuthenticatedSettingsAdminQuotasRouteImport.update({
    id: '/settings/admin-quotas',
    path: '/settings/admin-quotas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAdminSessionsRoute =
  AuthenticatedSettingsAdminSessionsRouteImport.update({
    id: '/settings/admin-sessions',
    path: '/settings/admin-sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAdminsRoute =
  AuthenticatedSettingsAdminsRouteImport.update({
    id: '/settings/admins',
    path: '/settings/admins',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPaymentChannelsRoute =
  AuthenticatedSettingsPaymentChannelsRouteImport.update({
    id: '/settings/payment-channels',
    path: '/settings/payment-channels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRolesPermissionRoute =
  AuthenticatedSettingsRolesPermissionRouteImport.update({
    id: '/settings/roles-permission',
    path: '/settings/roles-permission',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/games/categories': typeof AuthenticatedGamesCategoriesRoute
  '/games/ranking': typeof AuthenticatedGamesRankingRoute
  '/players/groups': typeof AuthenticatedPlayersGroupsRoute
  '/players/labels': typeof AuthenticatedPlayersLabelsRoute
  '/players/mobile-policy': typeof AuthenticatedPlayersMobilePolicyRoute
  '/players/self-limits': typeof AuthenticatedPlayersSelfLimitsRoute
  '/players/sessions': typeof AuthenticatedPlayersSessionsRoute
  '/promotions/banners': typeof AuthenticatedPromotionsBannersRoute
  '/promotions/bonuses': typeof AuthenticatedPromotionsBonusesRoute
  '/promotions/pages': typeof AuthenticatedPromotionsPagesRoute
  '/promotions/rebate-setting': typeof AuthenticatedPromotionsRebateSettingRoute
  '/promotions/rebate-trans': typeof AuthenticatedPromotionsRebateTransRoute
  '/promotions/transactions': typeof AuthenticatedPromotionsTransactionsRoute
  '/promotions/xp-shop': typeof AuthenticatedPromotionsXpShopRoute
  '/promotions/xp-shop-categories': typeof AuthenticatedPromotionsXpShopCategoriesRoute
  '/promotions/xp-shop-history': typeof AuthenticatedPromotionsXpShopHistoryRoute
  '/reports/acsc-reward-pushlog': typeof AuthenticatedReportsAcscRewardPushlogRoute
  '/reports/acsc-transfer': typeof AuthenticatedReportsAcscTransferRoute
  '/reports/bet-trans': typeof AuthenticatedReportsBetTransRoute
  '/reports/ledger-trans': typeof AuthenticatedReportsLedgerTransRoute
  '/reports/payment-transaction': typeof AuthenticatedReportsPaymentTransactionRoute
  '/reports/wager-stats': typeof AuthenticatedReportsWagerStatsRoute
  '/settings/admin-ops-logs': typeof AuthenticatedSettingsAdminOpsLogsRoute
  '/settings/admin-quota-configs': typeof AuthenticatedSettingsAdminQuotaConfigsRoute
  '/settings/admin-quotas': typeof AuthenticatedSettingsAdminQuotasRoute
  '/settings/admin-sessions': typeof AuthenticatedSettingsAdminSessionsRoute
  '/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/settings/payment-channels': typeof AuthenticatedSettingsPaymentChannelsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/roles-permission': typeof AuthenticatedSettingsRolesPermissionRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/promotions/': typeof AuthenticatedPromotionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/games/categories': typeof AuthenticatedGamesCategoriesRoute
  '/games/ranking': typeof AuthenticatedGamesRankingRoute
  '/players/groups': typeof AuthenticatedPlayersGroupsRoute
  '/players/labels': typeof AuthenticatedPlayersLabelsRoute
  '/players/mobile-policy': typeof AuthenticatedPlayersMobilePolicyRoute
  '/players/self-limits': typeof AuthenticatedPlayersSelfLimitsRoute
  '/players/sessions': typeof AuthenticatedPlayersSessionsRoute
  '/promotions/banners': typeof AuthenticatedPromotionsBannersRoute
  '/promotions/bonuses': typeof AuthenticatedPromotionsBonusesRoute
  '/promotions/pages': typeof AuthenticatedPromotionsPagesRoute
  '/promotions/rebate-setting': typeof AuthenticatedPromotionsRebateSettingRoute
  '/promotions/rebate-trans': typeof AuthenticatedPromotionsRebateTransRoute
  '/promotions/transactions': typeof AuthenticatedPromotionsTransactionsRoute
  '/promotions/xp-shop': typeof AuthenticatedPromotionsXpShopRoute
  '/promotions/xp-shop-categories': typeof AuthenticatedPromotionsXpShopCategoriesRoute
  '/promotions/xp-shop-history': typeof AuthenticatedPromotionsXpShopHistoryRoute
  '/reports/acsc-reward-pushlog': typeof AuthenticatedReportsAcscRewardPushlogRoute
  '/reports/acsc-transfer': typeof AuthenticatedReportsAcscTransferRoute
  '/reports/bet-trans': typeof AuthenticatedReportsBetTransRoute
  '/reports/ledger-trans': typeof AuthenticatedReportsLedgerTransRoute
  '/reports/payment-transaction': typeof AuthenticatedReportsPaymentTransactionRoute
  '/reports/wager-stats': typeof AuthenticatedReportsWagerStatsRoute
  '/settings/admin-ops-logs': typeof AuthenticatedSettingsAdminOpsLogsRoute
  '/settings/admin-quota-configs': typeof AuthenticatedSettingsAdminQuotaConfigsRoute
  '/settings/admin-quotas': typeof AuthenticatedSettingsAdminQuotasRoute
  '/settings/admin-sessions': typeof AuthenticatedSettingsAdminSessionsRoute
  '/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/settings/payment-channels': typeof AuthenticatedSettingsPaymentChannelsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/roles-permission': typeof AuthenticatedSettingsRolesPermissionRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/promotions': typeof AuthenticatedPromotionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/games/categories': typeof AuthenticatedGamesCategoriesRoute
  '/_authenticated/games/ranking': typeof AuthenticatedGamesRankingRoute
  '/_authenticated/players/groups': typeof AuthenticatedPlayersGroupsRoute
  '/_authenticated/players/labels': typeof AuthenticatedPlayersLabelsRoute
  '/_authenticated/players/mobile-policy': typeof AuthenticatedPlayersMobilePolicyRoute
  '/_authenticated/players/self-limits': typeof AuthenticatedPlayersSelfLimitsRoute
  '/_authenticated/players/sessions': typeof AuthenticatedPlayersSessionsRoute
  '/_authenticated/promotions/banners': typeof AuthenticatedPromotionsBannersRoute
  '/_authenticated/promotions/bonuses': typeof AuthenticatedPromotionsBonusesRoute
  '/_authenticated/promotions/pages': typeof AuthenticatedPromotionsPagesRoute
  '/_authenticated/promotions/rebate-setting': typeof AuthenticatedPromotionsRebateSettingRoute
  '/_authenticated/promotions/rebate-trans': typeof AuthenticatedPromotionsRebateTransRoute
  '/_authenticated/promotions/transactions': typeof AuthenticatedPromotionsTransactionsRoute
  '/_authenticated/promotions/xp-shop': typeof AuthenticatedPromotionsXpShopRoute
  '/_authenticated/promotions/xp-shop-categories': typeof AuthenticatedPromotionsXpShopCategoriesRoute
  '/_authenticated/promotions/xp-shop-history': typeof AuthenticatedPromotionsXpShopHistoryRoute
  '/_authenticated/reports/acsc-reward-pushlog': typeof AuthenticatedReportsAcscRewardPushlogRoute
  '/_authenticated/reports/acsc-transfer': typeof AuthenticatedReportsAcscTransferRoute
  '/_authenticated/reports/bet-trans': typeof AuthenticatedReportsBetTransRoute
  '/_authenticated/reports/ledger-trans': typeof AuthenticatedReportsLedgerTransRoute
  '/_authenticated/reports/payment-transaction': typeof AuthenticatedReportsPaymentTransactionRoute
  '/_authenticated/reports/wager-stats': typeof AuthenticatedReportsWagerStatsRoute
  '/_authenticated/settings/admin-ops-logs': typeof AuthenticatedSettingsAdminOpsLogsRoute
  '/_authenticated/settings/admin-quota-configs': typeof AuthenticatedSettingsAdminQuotaConfigsRoute
  '/_authenticated/settings/admin-quotas': typeof AuthenticatedSettingsAdminQuotasRoute
  '/_authenticated/settings/admin-sessions': typeof AuthenticatedSettingsAdminSessionsRoute
  '/_authenticated/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/_authenticated/settings/payment-channels': typeof AuthenticatedSettingsPaymentChannelsRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/roles-permission': typeof AuthenticatedSettingsRolesPermissionRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/promotions/': typeof AuthenticatedPromotionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/health'
    | '/games/categories'
    | '/games/ranking'
    | '/players/groups'
    | '/players/labels'
    | '/players/mobile-policy'
    | '/players/self-limits'
    | '/players/sessions'
    | '/promotions/banners'
    | '/promotions/bonuses'
    | '/promotions/pages'
    | '/promotions/rebate-setting'
    | '/promotions/rebate-trans'
    | '/promotions/transactions'
    | '/promotions/xp-shop'
    | '/promotions/xp-shop-categories'
    | '/promotions/xp-shop-history'
    | '/reports/acsc-reward-pushlog'
    | '/reports/acsc-transfer'
    | '/reports/bet-trans'
    | '/reports/ledger-trans'
    | '/reports/payment-transaction'
    | '/reports/wager-stats'
    | '/settings/admin-ops-logs'
    | '/settings/admin-quota-configs'
    | '/settings/admin-quotas'
    | '/settings/admin-sessions'
    | '/settings/admins'
    | '/settings/payment-channels'
    | '/settings/roles'
    | '/settings/roles-permission'
    | '/games/'
    | '/players/'
    | '/promotions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/health'
    | '/games/categories'
    | '/games/ranking'
    | '/players/groups'
    | '/players/labels'
    | '/players/mobile-policy'
    | '/players/self-limits'
    | '/players/sessions'
    | '/promotions/banners'
    | '/promotions/bonuses'
    | '/promotions/pages'
    | '/promotions/rebate-setting'
    | '/promotions/rebate-trans'
    | '/promotions/transactions'
    | '/promotions/xp-shop'
    | '/promotions/xp-shop-categories'
    | '/promotions/xp-shop-history'
    | '/reports/acsc-reward-pushlog'
    | '/reports/acsc-transfer'
    | '/reports/bet-trans'
    | '/reports/ledger-trans'
    | '/reports/payment-transaction'
    | '/reports/wager-stats'
    | '/settings/admin-ops-logs'
    | '/settings/admin-quota-configs'
    | '/settings/admin-quotas'
    | '/settings/admin-sessions'
    | '/settings/admins'
    | '/settings/payment-channels'
    | '/settings/roles'
    | '/settings/roles-permission'
    | '/games'
    | '/players'
    | '/promotions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/api/health'
    | '/_authenticated/games/categories'
    | '/_authenticated/games/ranking'
    | '/_authenticated/players/groups'
    | '/_authenticated/players/labels'
    | '/_authenticated/players/mobile-policy'
    | '/_authenticated/players/self-limits'
    | '/_authenticated/players/sessions'
    | '/_authenticated/promotions/banners'
    | '/_authenticated/promotions/bonuses'
    | '/_authenticated/promotions/pages'
    | '/_authenticated/promotions/rebate-setting'
    | '/_authenticated/promotions/rebate-trans'
    | '/_authenticated/promotions/transactions'
    | '/_authenticated/promotions/xp-shop'
    | '/_authenticated/promotions/xp-shop-categories'
    | '/_authenticated/promotions/xp-shop-history'
    | '/_authenticated/reports/acsc-reward-pushlog'
    | '/_authenticated/reports/acsc-transfer'
    | '/_authenticated/reports/bet-trans'
    | '/_authenticated/reports/ledger-trans'
    | '/_authenticated/reports/payment-transaction'
    | '/_authenticated/reports/wager-stats'
    | '/_authenticated/settings/admin-ops-logs'
    | '/_authenticated/settings/admin-quota-configs'
    | '/_authenticated/settings/admin-quotas'
    | '/_authenticated/settings/admin-sessions'
    | '/_authenticated/settings/admins'
    | '/_authenticated/settings/payment-channels'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/roles-permission'
    | '/_authenticated/games/'
    | '/_authenticated/players/'
    | '/_authenticated/promotions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/categories': {
      id: '/_authenticated/games/categories'
      path: '/games/categories'
      fullPath: '/games/categories'
      preLoaderRoute: typeof AuthenticatedGamesCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/ranking': {
      id: '/_authenticated/games/ranking'
      path: '/games/ranking'
      fullPath: '/games/ranking'
      preLoaderRoute: typeof AuthenticatedGamesRankingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/groups': {
      id: '/_authenticated/players/groups'
      path: '/players/groups'
      fullPath: '/players/groups'
      preLoaderRoute: typeof AuthenticatedPlayersGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/labels': {
      id: '/_authenticated/players/labels'
      path: '/players/labels'
      fullPath: '/players/labels'
      preLoaderRoute: typeof AuthenticatedPlayersLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/mobile-policy': {
      id: '/_authenticated/players/mobile-policy'
      path: '/players/mobile-policy'
      fullPath: '/players/mobile-policy'
      preLoaderRoute: typeof AuthenticatedPlayersMobilePolicyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/self-limits': {
      id: '/_authenticated/players/self-limits'
      path: '/players/self-limits'
      fullPath: '/players/self-limits'
      preLoaderRoute: typeof AuthenticatedPlayersSelfLimitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/sessions': {
      id: '/_authenticated/players/sessions'
      path: '/players/sessions'
      fullPath: '/players/sessions'
      preLoaderRoute: typeof AuthenticatedPlayersSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/': {
      id: '/_authenticated/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof AuthenticatedPromotionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/banners': {
      id: '/_authenticated/promotions/banners'
      path: '/promotions/banners'
      fullPath: '/promotions/banners'
      preLoaderRoute: typeof AuthenticatedPromotionsBannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/bonuses': {
      id: '/_authenticated/promotions/bonuses'
      path: '/promotions/bonuses'
      fullPath: '/promotions/bonuses'
      preLoaderRoute: typeof AuthenticatedPromotionsBonusesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/pages': {
      id: '/_authenticated/promotions/pages'
      path: '/promotions/pages'
      fullPath: '/promotions/pages'
      preLoaderRoute: typeof AuthenticatedPromotionsPagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/rebate-setting': {
      id: '/_authenticated/promotions/rebate-setting'
      path: '/promotions/rebate-setting'
      fullPath: '/promotions/rebate-setting'
      preLoaderRoute: typeof AuthenticatedPromotionsRebateSettingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/rebate-trans': {
      id: '/_authenticated/promotions/rebate-trans'
      path: '/promotions/rebate-trans'
      fullPath: '/promotions/rebate-trans'
      preLoaderRoute: typeof AuthenticatedPromotionsRebateTransRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/transactions': {
      id: '/_authenticated/promotions/transactions'
      path: '/promotions/transactions'
      fullPath: '/promotions/transactions'
      preLoaderRoute: typeof AuthenticatedPromotionsTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/xp-shop': {
      id: '/_authenticated/promotions/xp-shop'
      path: '/promotions/xp-shop'
      fullPath: '/promotions/xp-shop'
      preLoaderRoute: typeof AuthenticatedPromotionsXpShopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/xp-shop-categories': {
      id: '/_authenticated/promotions/xp-shop-categories'
      path: '/promotions/xp-shop-categories'
      fullPath: '/promotions/xp-shop-categories'
      preLoaderRoute: typeof AuthenticatedPromotionsXpShopCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions/xp-shop-history': {
      id: '/_authenticated/promotions/xp-shop-history'
      path: '/promotions/xp-shop-history'
      fullPath: '/promotions/xp-shop-history'
      preLoaderRoute: typeof AuthenticatedPromotionsXpShopHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/acsc-reward-pushlog': {
      id: '/_authenticated/reports/acsc-reward-pushlog'
      path: '/reports/acsc-reward-pushlog'
      fullPath: '/reports/acsc-reward-pushlog'
      preLoaderRoute: typeof AuthenticatedReportsAcscRewardPushlogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/acsc-transfer': {
      id: '/_authenticated/reports/acsc-transfer'
      path: '/reports/acsc-transfer'
      fullPath: '/reports/acsc-transfer'
      preLoaderRoute: typeof AuthenticatedReportsAcscTransferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/bet-trans': {
      id: '/_authenticated/reports/bet-trans'
      path: '/reports/bet-trans'
      fullPath: '/reports/bet-trans'
      preLoaderRoute: typeof AuthenticatedReportsBetTransRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/ledger-trans': {
      id: '/_authenticated/reports/ledger-trans'
      path: '/reports/ledger-trans'
      fullPath: '/reports/ledger-trans'
      preLoaderRoute: typeof AuthenticatedReportsLedgerTransRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/payment-transaction': {
      id: '/_authenticated/reports/payment-transaction'
      path: '/reports/payment-transaction'
      fullPath: '/reports/payment-transaction'
      preLoaderRoute: typeof AuthenticatedReportsPaymentTransactionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/wager-stats': {
      id: '/_authenticated/reports/wager-stats'
      path: '/reports/wager-stats'
      fullPath: '/reports/wager-stats'
      preLoaderRoute: typeof AuthenticatedReportsWagerStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/admin-ops-logs': {
      id: '/_authenticated/settings/admin-ops-logs'
      path: '/settings/admin-ops-logs'
      fullPath: '/settings/admin-ops-logs'
      preLoaderRoute: typeof AuthenticatedSettingsAdminOpsLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/admin-quota-configs': {
      id: '/_authenticated/settings/admin-quota-configs'
      path: '/settings/admin-quota-configs'
      fullPath: '/settings/admin-quota-configs'
      preLoaderRoute: typeof AuthenticatedSettingsAdminQuotaConfigsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/admin-quotas': {
      id: '/_authenticated/settings/admin-quotas'
      path: '/settings/admin-quotas'
      fullPath: '/settings/admin-quotas'
      preLoaderRoute: typeof AuthenticatedSettingsAdminQuotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/admin-sessions': {
      id: '/_authenticated/settings/admin-sessions'
      path: '/settings/admin-sessions'
      fullPath: '/settings/admin-sessions'
      preLoaderRoute: typeof AuthenticatedSettingsAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/admins': {
      id: '/_authenticated/settings/admins'
      path: '/settings/admins'
      fullPath: '/settings/admins'
      preLoaderRoute: typeof AuthenticatedSettingsAdminsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/payment-channels': {
      id: '/_authenticated/settings/payment-channels'
      path: '/settings/payment-channels'
      fullPath: '/settings/payment-channels'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/roles-permission': {
      id: '/_authenticated/settings/roles-permission'
      path: '/settings/roles-permission'
      fullPath: '/settings/roles-permission'
      preLoaderRoute: typeof AuthenticatedSettingsRolesPermissionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGamesCategoriesRoute: typeof AuthenticatedGamesCategoriesRoute
  AuthenticatedGamesRankingRoute: typeof AuthenticatedGamesRankingRoute
  AuthenticatedPlayersGroupsRoute: typeof AuthenticatedPlayersGroupsRoute
  AuthenticatedPlayersLabelsRoute: typeof AuthenticatedPlayersLabelsRoute
  AuthenticatedPlayersMobilePolicyRoute: typeof AuthenticatedPlayersMobilePolicyRoute
  AuthenticatedPlayersSelfLimitsRoute: typeof AuthenticatedPlayersSelfLimitsRoute
  AuthenticatedPlayersSessionsRoute: typeof AuthenticatedPlayersSessionsRoute
  AuthenticatedPromotionsBannersRoute: typeof AuthenticatedPromotionsBannersRoute
  AuthenticatedPromotionsBonusesRoute: typeof AuthenticatedPromotionsBonusesRoute
  AuthenticatedPromotionsPagesRoute: typeof AuthenticatedPromotionsPagesRoute
  AuthenticatedPromotionsRebateSettingRoute: typeof AuthenticatedPromotionsRebateSettingRoute
  AuthenticatedPromotionsRebateTransRoute: typeof AuthenticatedPromotionsRebateTransRoute
  AuthenticatedPromotionsTransactionsRoute: typeof AuthenticatedPromotionsTransactionsRoute
  AuthenticatedPromotionsXpShopRoute: typeof AuthenticatedPromotionsXpShopRoute
  AuthenticatedPromotionsXpShopCategoriesRoute: typeof AuthenticatedPromotionsXpShopCategoriesRoute
  AuthenticatedPromotionsXpShopHistoryRoute: typeof AuthenticatedPromotionsXpShopHistoryRoute
  AuthenticatedReportsAcscRewardPushlogRoute: typeof AuthenticatedReportsAcscRewardPushlogRoute
  AuthenticatedReportsAcscTransferRoute: typeof AuthenticatedReportsAcscTransferRoute
  AuthenticatedReportsBetTransRoute: typeof AuthenticatedReportsBetTransRoute
  AuthenticatedReportsLedgerTransRoute: typeof AuthenticatedReportsLedgerTransRoute
  AuthenticatedReportsPaymentTransactionRoute: typeof AuthenticatedReportsPaymentTransactionRoute
  AuthenticatedReportsWagerStatsRoute: typeof AuthenticatedReportsWagerStatsRoute
  AuthenticatedSettingsAdminOpsLogsRoute: typeof AuthenticatedSettingsAdminOpsLogsRoute
  AuthenticatedSettingsAdminQuotaConfigsRoute: typeof AuthenticatedSettingsAdminQuotaConfigsRoute
  AuthenticatedSettingsAdminQuotasRoute: typeof AuthenticatedSettingsAdminQuotasRoute
  AuthenticatedSettingsAdminSessionsRoute: typeof AuthenticatedSettingsAdminSessionsRoute
  AuthenticatedSettingsAdminsRoute: typeof AuthenticatedSettingsAdminsRoute
  AuthenticatedSettingsPaymentChannelsRoute: typeof AuthenticatedSettingsPaymentChannelsRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsRolesPermissionRoute: typeof AuthenticatedSettingsRolesPermissionRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
  AuthenticatedPromotionsIndexRoute: typeof AuthenticatedPromotionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGamesCategoriesRoute: AuthenticatedGamesCategoriesRoute,
  AuthenticatedGamesRankingRoute: AuthenticatedGamesRankingRoute,
  AuthenticatedPlayersGroupsRoute: AuthenticatedPlayersGroupsRoute,
  AuthenticatedPlayersLabelsRoute: AuthenticatedPlayersLabelsRoute,
  AuthenticatedPlayersMobilePolicyRoute: AuthenticatedPlayersMobilePolicyRoute,
  AuthenticatedPlayersSelfLimitsRoute: AuthenticatedPlayersSelfLimitsRoute,
  AuthenticatedPlayersSessionsRoute: AuthenticatedPlayersSessionsRoute,
  AuthenticatedPromotionsBannersRoute: AuthenticatedPromotionsBannersRoute,
  AuthenticatedPromotionsBonusesRoute: AuthenticatedPromotionsBonusesRoute,
  AuthenticatedPromotionsPagesRoute: AuthenticatedPromotionsPagesRoute,
  AuthenticatedPromotionsRebateSettingRoute:
    AuthenticatedPromotionsRebateSettingRoute,
  AuthenticatedPromotionsRebateTransRoute:
    AuthenticatedPromotionsRebateTransRoute,
  AuthenticatedPromotionsTransactionsRoute:
    AuthenticatedPromotionsTransactionsRoute,
  AuthenticatedPromotionsXpShopRoute: AuthenticatedPromotionsXpShopRoute,
  AuthenticatedPromotionsXpShopCategoriesRoute:
    AuthenticatedPromotionsXpShopCategoriesRoute,
  AuthenticatedPromotionsXpShopHistoryRoute:
    AuthenticatedPromotionsXpShopHistoryRoute,
  AuthenticatedReportsAcscRewardPushlogRoute:
    AuthenticatedReportsAcscRewardPushlogRoute,
  AuthenticatedReportsAcscTransferRoute: AuthenticatedReportsAcscTransferRoute,
  AuthenticatedReportsBetTransRoute: AuthenticatedReportsBetTransRoute,
  AuthenticatedReportsLedgerTransRoute: AuthenticatedReportsLedgerTransRoute,
  AuthenticatedReportsPaymentTransactionRoute:
    AuthenticatedReportsPaymentTransactionRoute,
  AuthenticatedReportsWagerStatsRoute: AuthenticatedReportsWagerStatsRoute,
  AuthenticatedSettingsAdminOpsLogsRoute:
    AuthenticatedSettingsAdminOpsLogsRoute,
  AuthenticatedSettingsAdminQuotaConfigsRoute:
    AuthenticatedSettingsAdminQuotaConfigsRoute,
  AuthenticatedSettingsAdminQuotasRoute: AuthenticatedSettingsAdminQuotasRoute,
  AuthenticatedSettingsAdminSessionsRoute:
    AuthenticatedSettingsAdminSessionsRoute,
  AuthenticatedSettingsAdminsRoute: AuthenticatedSettingsAdminsRoute,
  AuthenticatedSettingsPaymentChannelsRoute:
    AuthenticatedSettingsPaymentChannelsRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsRolesPermissionRoute:
    AuthenticatedSettingsRolesPermissionRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  AuthenticatedPromotionsIndexRoute: AuthenticatedPromotionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
